baseURL = 'https://morriswong.github.io/test-blog/'
languageCode = 'en-us'
title = 'My Blog'
theme = 'PaperMod'

[params]
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = true

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/morriswong"
