baseURL = 'https://test-blog-8s6.pages.dev/'
languageCode = 'en-us'
title = "Morris Wong's Blog"
theme = 'PaperMod'

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params]
  mainSections = ["posts"]
  description = "Dev • Life • Canto"
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = true
  ShowTags = true

[[menu.main]]
  name = "Tags"
  url = "/tags/"
  weight = 1

[[menu.main]]
  name = "Archive"
  url = "/archives/"
  weight = 2

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/morriswong"

[[params.socialIcons]]
  name = "rss"
  url = "/index.xml"
