baseURL = 'https://test-blog-8s6.pages.dev/'
languageCode = 'en-us'
title = 'My Blog'
theme = 'yinyang'

[author]
  name = "Morris Wong"
  homepage = "https://github.com/morriswong"

[params]
  mainSections = ["posts"]

[[params.socials]]
  name = "GitHub"
  link = "https://github.com/morriswong"

[[params.socials]]
  name = "RSS"
  link = "/index.xml"
