baseURL = 'https://test-blog-8s6.pages.dev/'
languageCode = 'en-us'
title = "morwon"

copyright = "Copyright © 2025 Morris Wong. All rights reserved."

theme = "dario"

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params]
  mainSections = ["posts"]
  description = "Dev • Life • Canto"

  [params.author]
    name = "Morris Wong"
    email = "morriswch@gmail.com"
