baseURL = 'https://test-blog-8s6.pages.dev/'
languageCode = 'en-us'
title = 'My Blog'
theme = 'yinyang'

[author]
  name = "Morris Wong"
  homepage = "https://github.com/morriswong"

[params]
  mainSections = ["dev"]

[[menu.main]]
  name = "Dev"
  url = "/dev/"
  weight = 1

[[menu.main]]
  name = "Life"
  url = "/life/"
  weight = 2

[[menu.main]]
  name = "Canto"
  url = "/canto/"
  weight = 3

[[params.socials]]
  name = "GitHub"
  link = "https://github.com/morriswong"

[[params.socials]]
  name = "RSS"
  link = "/index.xml"
