name = "test-blog-oauth"
main = "oauth.js"
compatibility_date = "2024-01-01"

# You'll need to set these secrets using:
# wrangler secret put GITHUB_CLIENT_ID
# wrangler secret put GITHUB_CLIENT_SECRET

[vars]
# Add any non-secret environment variables here if needed
